# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "acts_as_diffable"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["James Mason 'bear454'"]
  s.date = "2012-04-19"
  s.description = "ActsAsDiffable provides a dead-simple way to compare two instances of a class, including any or all associations, or more complex relationships."
  s.email = "jmason@suse.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/acts_as_diffable.rb",
    "test/app_root/app/controllers/application_controller.rb",
    "test/app_root/app/models/group.rb",
    "test/app_root/app/models/tag.rb",
    "test/app_root/app/models/user.rb",
    "test/app_root/config/boot.rb",
    "test/app_root/config/database.yml",
    "test/app_root/config/environment.rb",
    "test/app_root/config/environments/in_memory.rb",
    "test/app_root/config/environments/mysql.rb",
    "test/app_root/config/environments/postgresql.rb",
    "test/app_root/config/environments/sqlite.rb",
    "test/app_root/config/environments/sqlite3.rb",
    "test/app_root/config/routes.rb",
    "test/app_root/db/migrate/20101117081517_create_users.rb",
    "test/app_root/db/migrate/20101117081553_create_groups.rb",
    "test/app_root/db/migrate/20101117081632_create_tags.rb",
    "test/app_root/lib/console_with_fixtures.rb",
    "test/app_root/log/.gitignore",
    "test/app_root/script/console",
    "test/diff_test.rb",
    "test/fixtures/groups.yml",
    "test/fixtures/tags.yml",
    "test/fixtures/users.yml",
    "test/test_helper.rb"
  ]
  s.homepage = "https://github.com/bear454/ActsAsDiffable"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.22"
  s.summary = "Compare two instances of an ActiveRecord::Base class."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.14"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.3.14"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.3.14"])
  end
end

